import type { Product } from "../types/product";

const API_URL = "https://api.sheety.co/e47dcae5ed33aa21c3b1cad5e3644552/productDb/sheet1";

// Helper function to get local image path
const getImagePath = (imageName: string): string => {
  // If it's already a full URL, return as is
  if (imageName.startsWith('http://') || imageName.startsWith('https://')) {
    return imageName;
  }
  
  // If it's a local path starting with /assets or ./assets
  if (imageName.startsWith('/assets/') || imageName.startsWith('assets/') || imageName.startsWith('./assets/')) {
    return imageName;
  }
  
  // If it's just a filename, assume it's in assets/products
  if (imageName && !imageName.includes('/')) {
    return `/assets/products/${imageName}`;
  }
  
  // Fallback image
  return "https://lh3.googleusercontent.com/d/10HjlsEvL5hDly9cUxv50Zh-btvFU0_us";
};

export const getProducts = async (): Promise<Product[]> => {
  try {
    const response = await fetch(API_URL);
    if (!response.ok) throw new Error("Network response was not ok");
    
    const data = await response.json();
    
    // Remap data safely looking for both camelCase and absolute lowercase keys generated by Sheety
    return (data.sheet1 || []).map((item: any) => ({
      id: Number(item.id), 
      name: {
        en: item.nameEn || item.nameen || item.name || "",
        km: item.nameKm || item.namekm || ""
      },
      category: {
        en: item.categoryEn || item.categoryen || item.category || "",
        km: item.categoryKm || item.categorykm || ""
      },
      description: {
        en: item.descriptionEn || item.descriptionen || item.description || "",
        km: item.descriptionKm || item.descriptionkm || ""
      },
      price: Number(item.price) || 0,
      image: getImagePath(item.image || ""),
    }));
  } catch (error) {
    console.error("Error fetching live inventory:", error);
    return [];
  }
};

// 2. ADD A NEW PRODUCT (ADMIN ACTIONS)
export const addProduct = async (productData: Omit<Product, "id">): Promise<boolean> => {
  const payload = {
    sheet1: {
      nameEn: productData.name.en,
      nameKm: productData.name.km,
      categoryEn: productData.category.en,
      categoryKm: productData.category.km,
      descriptionEn: productData.description?.en || "",
      descriptionKm: productData.description?.km || "",
      price: productData.price,
      image: productData.image
    }
  };

  try {
    const response = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });
    return response.ok;
  } catch (error) {
    console.error("Error adding product row:", error);
    return false;
  }
};

// 3. REMOVE A PRODUCT BY ID
export const deleteProduct = async (id: number): Promise<boolean> => {
  try {
    const response = await fetch(`${API_URL}/${id}`, {
      method: "DELETE"
    });
    return response.ok;
  } catch (error) {
    console.error("Error deleting product row:", error);
    return false;
  }
};

// Static hardcoded categories layout for navigation UI filtering
export const categories = [
  { en: "All", km: "ទាំងអស់" },
  { en: "ត្រីងៀត", km: "ត្រីងៀត" },
  { en: "ត្រីឆ្អើរ", km: "ត្រីឆ្អើរ" },
  { en: "Chicken", km: "សាច់មាន់" }
];